MoneyLoverTUBUI/Controllers/STKsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MoneyLoverTUBUI;

namespace MoneyLoverTUBUI.Controllers
{
    public class STKsController : Controller
    {
        private Entities db = new Entities();

        // GET: STKs
        public ActionResult Index()
        {
            var sTKs = db.STKs.Include(s => s.AspNetUser);
            return View(sTKs.ToList());
        }

        // GET: STKs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            STK sTK = db.STKs.Find(id);
            if (sTK == null)
            {
                return HttpNotFound();
            }
            return View(sTK);
        }

        // GET: STKs/Create
        public ActionResult Create()
        {
            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email");
            return View();
        }

        // POST: STKs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdSTK,UserID,NganHang,NgayGui,SoTienGoc,KyHanGui,LaiSuat,LaiSuatKhongKyHan,TraLai,KhiDenHan,TinhTrang")] STK sTK)
        {
            if (ModelState.IsValid)
            {
                db.STKs.Add(sTK);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email", sTK.UserID);
            return View(sTK);
        }

        // GET: STKs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            STK sTK = db.STKs.Find(id);
            if (sTK == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email", sTK.UserID);
            return View(sTK);
        }

        // POST: STKs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdSTK,UserID,NganHang,NgayGui,SoTienGoc,KyHanGui,LaiSuat,LaiSuatKhongKyHan,TraLai,KhiDenHan,TinhTrang")] STK sTK)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sTK).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email", sTK.UserID);
            return View(sTK);
        }

        // GET: STKs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            STK sTK = db.STKs.Find(id);
            if (sTK == null)
            {
                return HttpNotFound();
            }
            return View(sTK);
        }

        // POST: STKs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            STK sTK = db.STKs.Find(id);
            db.STKs.Remove(sTK);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult DangNhap()
        {
            return View();
        }
        public ActionResult DangKy()
        {
            return View();
        }
        public ActionResult Tattoan(int? id)
        {
            if (id == null)
            {
                ViewBag.Message = "thao tác thất bại , id không thể trống ";
                TempData["AlertFail"] = "<script>document.getElementById('alertboxFail').style.display = 'block'</script>";
                return View("Index");
            }
            STK sTK = db.STKs.Find(id);
            if (sTK.TinhTrang == "Close")
            {
                ViewBag.Message = "sổ đã đóng , không thể tất toán nữa";
                TempData["AlertFail"] = "<script>document.getElementById('alertboxFail').style.display = 'block'</script>";
                return View("Index");
            }
            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email", sTK.UserID);
            ViewBag.idstk = id;
            return View(sTK);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Tattoaninput(int? id)
        {
            if (id == null)
            {
                ViewBag.Message = "id rỗng";
                TempData["AlertFail"] = "<script>document.getElementById('alertboxFail').style.display = 'block'</script>";
                return View("Index");
            }
            STK sTK = db.STKs.Find(id);
            bool idtontai = false;
            foreach(var item in db.STKs)
            {
                if (id == item.IdSTK) { idtontai = true; }
            }
            if (idtontai && sTK.TinhTrang =="Open")
            {
                sTK.TinhTrang = "Close";
                sTK.TienLai = (int)(sTK.SoTienGoc * sTK.LaiSuatKhongKyHan * (DateTime.Now - (DateTime)sTK.NgayGui).TotalDays / 365) ;
                db.Entry(sTK).State = EntityState.Modified;
                db.SaveChanges();
                ViewBag.TinhTrang = sTK.TinhTrang;
                ViewBag.TienLai = sTK.TienLai;
                ViewBag.Message = "tất toán thành công , tiền lãi của bạn là :"+ sTK.TienLai;
                TempData["AlertSuccess"] = "<script>document.getElementById('alertboxSucess').style.display = 'block'</script>";
                return View("Index");
            }
            if (idtontai && sTK.TinhTrang =="Close")
            {
                ViewBag.TinhTrang = sTK.TinhTrang;
                ViewBag.TienLai = sTK.TienLai;
                ViewBag.Message = "Thao tác thất bại, bạn không thể tất toán sổ đã đóng";
                TempData["AlertFail"] = "<script>document.getElementById('alertboxFail').style.display = 'block'</script>";
                return View("Index");
            }
            if (idtontai == false)
            {
                ViewBag.Message = "id không tồn tại";
                TempData["AlertFail"] = "<script>document.getElementById('alertboxFail').style.display = 'block'</script>";
                return View("Index");
            }

            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email", sTK.UserID);
            return View(sTK);
        }
        public ActionResult Guithem(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            STK sTK = db.STKs.Find(id);
            if (sTK == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email", sTK.UserID);
            ViewBag.stkID = id;
            return View(sTK);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Guithem([Bind(Include = "IdSTK,UserID,NganHang,NgayGui,SoTienGoc,KyHanGui,LaiSuat,LaiSuatKhongKyHan,TraLai,KhiDenHan,TinhTrang")] STK sTK, [Bind(Include = "sotiengui")]int soTiengui)
        {
            if (ModelState.IsValid)
            {

                sTK.SoTienGoc = sTK.SoTienGoc + soTiengui;
                db.Entry(sTK).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email", sTK.UserID);
            return View(sTK);
        }
        public ActionResult Rutmotphan(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            STK sTK = db.STKs.Find(id);
            if (sTK == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email", sTK.UserID);
            ViewBag.stkID = id;
            return View(sTK);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Rutmotphan([Bind(Include = "IdSTK,UserID,NganHang,NgayGui,SoTienGoc,KyHanGui,LaiSuat,LaiSuatKhongKyHan,TraLai,KhiDenHan,TinhTrang")] STK sTK,[Bind(Include ="sotienrut")]int soTienRut)
        {
            if (ModelState.IsValid)
            {
                sTK.SoTienGoc = sTK.SoTienGoc - soTienRut;
                db.Entry(sTK).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "Email", sTK.UserID);
            return View(sTK);
        }
    }
}

MoneyLoverTUBUI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated == false)
{
    Response.Redirect("~/Home/TrangGioiThieu", false);
}

<!DOCTYPE html>
<html>
<head>
    <title>Quản Lý Sổ Tiết Kiệm Cá Nhân</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Content/w3.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>
        html, body, h1, h2, h3, h4, h5 {
            font-family: "Raleway", sans-serif
        }
    </style>

</head>
<body class="w3-light-grey">
    <div class="w3-bar w3-top w3-black w3-large" style="z-index:4">
        <button class="w3-bar-item w3-button w3-hide-large w3-hover-none w3-hover-text-light-grey " onclick="w3_open();"><i class="fa fa-bars"></i>  Menu</button>
        <div class="w3-right ">
            @Html.ActionLink("Trang Chủ", "Index", "STKs", null, htmlAttributes: new { style = "font-size:35px",@class="w3-text-white" })
        </div>
        


    </div>
    <nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;" id="mySidebar">
        <br>
        <div class="w3-container w3-row">
            <div class="w3-col s4">
                @*<img src="/w3images/avatar2.png" class="w3-circle w3-margin-right" style="width:46px">*@
            </div>
            <div class="w3-col s8 w3-bar">
                <span>Xin chào !!, <strong>@User.Identity.GetUserName()</strong></span><br>
                <a href="~/Manage/ChangePassword" class="w3-bar-item w3-button"><i class="fa fa-cog"></i></a>
            </div>
        </div>
        <hr>
        <div class="w3-container">
            <h5>Quản Lý Sổ Tiết Kiệm</h5>
        </div>
        <div class="w3-bar-block">
            <a href="~/STKs/Create" class="w3-bar-item w3-button w3-padding"><i class="fa fa-users fa-fw"></i> Thêm số tiết kiệm </a>
            <a href="~/STKs/Index" class="w3-bar-item w3-button w3-padding"><i class="fa fa-eye fa-fw"></i>  Xem sổ tiết kiệm </a>
            @*<button class="w3-bar-item w3-button w3-hide-large w3-hover-none w3-hover-text-light-grey" onclick="w3_open();"><i class="fa fa-bars"></i>  Menu</button>*@
            @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "" }))
            {
                @Html.AntiForgeryToken()

                <a href="javascript:document.getElementById('logoutForm').submit()" class="w3-bar-item w3-button w3-padding"><i class="fa fa-sign-out fa-fw"></i> Đăng Xuất</a>
            }
            <a href="#" class="w3-bar-item w3-button w3-padding-16 w3-hide-large  w3-hover-black" onclick="w3_close()" title="close menu"><i class="fa fa-remove fa-fw"></i>  Close Menu</a>

        </div>
    </nav>
    <div class="w3-main w3-container" style="margin-left:300px;margin-top:43px;">
        @RenderBody()
        <hr />
        <footer></footer>
    </div>
    <script>
        // Get the Sidebar
        var mySidebar = document.getElementById("mySidebar");

        // Get the DIV with overlay effect
        var overlayBg = document.getElementById("myOverlay");

        // Toggle between showing and hiding the sidebar, and add overlay effect
        function w3_open() {
            if (mySidebar.style.display === 'block') {
                mySidebar.style.display = 'none';
                overlayBg.style.display = "none";
            } else {
                mySidebar.style.display = 'block';
                overlayBg.style.display = "block";
            }
        }

        // Close the sidebar with the close button
        function w3_close() {
            mySidebar.style.display = "none";
            overlayBg.style.display = "none";
        }
    </script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>